connectRobot;
offboard_mode;
tftree = rostf;
pause(1);
desiredPointPartnerFrame = [-1; 0; 0];
mapToPartner = getTransform(tftree, 'map', 'partner');
mapToPartnerTranslation = [mapToPartner.Transform.Translation.X; ...
                           mapToPartner.Transform.Translation.Y;...
                           mapToPartner.Transform.Translation.Z];
mapToPartnerRotation = [mapToPartner.Transform.Rotation.W,...
                        mapToPartner.Transform.Rotation.X,...
                        mapToPartner.Transform.Rotation.Y,...
                        mapToPartner.Transform.Rotation.Z];
desiredPointMapFrame = mapToPartnerTranslation + ...
                       quat2rotm(mapToPartnerRotation)*desiredPointPartnerFrame;
publishSetpoint(desiredPointMapFrame, eul2quat([0,0,0]))