function [time, pos, rpy]=processTransforms(transforms)
time = [cellfun(@(m) m.timestamp, transforms)];
pos = [cellfun(@(m) m.translation(1), transforms),...
         cellfun(@(m) m.translation(2), transforms),...
         cellfun(@(m) m.translation(3), transforms)];
[yaw, pitch, roll] = quat2angle(...
                     [cellfun(@(m) m.rotation(1), transforms),...
                      cellfun(@(m) m.rotation(2), transforms),...
                      cellfun(@(m) m.rotation(3), transforms),...
                      cellfun(@(m) m.rotation(4), transforms)], 'ZYX');
rpy = [roll pitch yaw];
end