function [pos, rpy]=processGazeboStates(msgs, index)
pos = [cellfun(@(m) m.Pose(index).Position.X, msgs),...
         cellfun(@(m) m.Pose(index).Position.Y, msgs),...
         cellfun(@(m) m.Pose(index).Position.Z, msgs)];
[yaw, pitch, roll] = quat2angle(...
                     [cellfun(@(m) m.Pose(index).Orientation.W, msgs),...
                      cellfun(@(m) m.Pose(index).Orientation.X, msgs),...
                      cellfun(@(m) m.Pose(index).Orientation.Y, msgs),...
                      cellfun(@(m) m.Pose(index).Orientation.Z, msgs)]);
rpy = [roll pitch yaw];
end