function [time, pos, rpy]=processTransforms(transforms)
time = [cellfun(@(m) m.Transforms.Header.Stamp.Sec + m.Transforms.Header.Stamp.Nsec/10^9, transforms)];
pos = [cellfun(@(m) m.Transforms.Transform.Translation.X, transforms),...
         cellfun(@(m) m.Transforms.Transform.Translation.Y, transforms),...
         cellfun(@(m) m.Transforms.Transform.Translation.Z, transforms)];
[yaw, pitch, roll] = quat2angle(...
                     [cellfun(@(m) m.Transforms.Transform.Rotation.W, transforms),...
                      cellfun(@(m) m.Transforms.Transform.Rotation.X, transforms),...
                      cellfun(@(m) m.Transforms.Transform.Rotation.Y, transforms),...
                      cellfun(@(m) m.Transforms.Transform.Rotation.Z, transforms)]);
rpy = [roll pitch yaw];
end